added documentation header to comms.ts
beyond-all-reason/bar-lobby pull request #199
Opened 2023-04-12 06:03 UTC by knoxy5467

Added some documentation as lined in my last pull request #198

2023-04-12 09:08 UTC, Jazcash requested changes

2023-04-12 09:08 UTC, Jazcash commented on src/renderer/api/comms.ts
> + * @classdesc Comms API
Can you remove this fluff? I'm keen on adding more overview documentation to classes, but I'd like to keep it to only the bare necessitities. If we ever get into auto-generating frontend documentation based on the code comments, a lot should be able to be inferred from Typescript.

Looking as JSDoc, I think this should probably be:
```
@fileoverview This class is a extension of the TachyonClient class. It is used to communicate with the server. All communication with the server should be done through this class, includeing matchmaking, chat, direct messages, and other lobby related functions.
```

2023-04-13 00:29 UTC, knoxy5467 commented
Ok will do.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Jazcash ***@***.***>
Sent: Wednesday, April 12, 2023 5:08:26 AM
To: beyond-all-reason/bar-lobby ***@***.***>
Cc: knoxy5467 ***@***.***>; Author ***@***.***>
Subject: Re: [beyond-all-reason/bar-lobby] added documentation header to comms.ts (PR #199)


@Jazcash requested changes on this pull request.

________________________________

In src/renderer/api/comms.ts<https://github.com/beyond-all-reason/bar-lobby/pull/199#discussion_r1163845566>:

> + * This documentation comment created on 12APR2023 by @knoxy5467
+ *
+ * last updated on 12APR2023 by @knoxy5467
+ *
+ * @class CommsAPI
+ * @classdesc Comms API


Can you remove this fluff? I'm keen on adding more overview documentation to classes, but I'd like to keep it to only the bare necessitities. If we ever get into auto-generating frontend documentation based on the code comments, a lot should be able to be inferred from Typescript.

Looking as JSDoc, I think this should probably be:

@fileoverview This class is a extension of the TachyonClient class. It is used to communicate with the server. All communication with the server should be done through this class, includeing matchmaking, chat, direct messages, and other lobby related functions.


—
Reply to this email directly, view it on GitHub<https://github.com/beyond-all-reason/bar-lobby/pull/199#pullrequestreview-1380869585>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABM6WLMB3TY3VSOFJHUK23TXAZWIVANCNFSM6AAAAAAW3GLBME>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-04-13 00:35 UTC, knoxy5467 commented
Done removed the fluff

2023-04-13 08:28 UTC, merged